#!/usr/bin/env python3
"""Generate the environment-variable reference table for docs/configuration.md.

The pydantic-settings model in src/nmem_immune/config.py is the authoritative source:
every field carries its canonical env var (env_prefix + FIELD upper-cased), default, type,
and a ``description``. This script introspects the model directly, so the reference can't
drift from the code.

    python scripts/gen_config_reference.py            # print the reference block
    python scripts/gen_config_reference.py --write     # splice it into docs/configuration.md
"""
import importlib.util
import re
import sys
from pathlib import Path
from typing import get_args, get_origin

from pydantic_core import PydanticUndefined
from pydantic_settings import BaseSettings

CONFIG_REL = "src/nmem_immune/config.py"
_ROOT = Path(__file__).resolve().parents[1]
_CONFIG_PATH = _ROOT / CONFIG_REL
_DOC_PATH = _ROOT / "docs/configuration.md"
_MARKER = "generated by scripts/gen_config_reference.py"

_spec = importlib.util.spec_from_file_location("_cfg_for_ref", _CONFIG_PATH)
config = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(config)

MODEL = next(
    v for v in vars(config).values()
    if isinstance(v, type) and issubclass(v, BaseSettings) and v is not BaseSettings
)
PREFIX = MODEL.model_config.get("env_prefix", "")

_SEC = re.compile(r"^\s*#\s*[─-]{2,}\s*(.+?)\s*[─-]*\s*$")
_FIELD = re.compile(r"^    ([a-z][a-z0-9_]*)\s*:")


def _field_sections() -> dict[str, str]:
    section, out = "General", {}
    for line in _CONFIG_PATH.read_text().splitlines():
        m = _SEC.match(line)
        if m and line.lstrip().startswith("#"):
            section = m.group(1).strip()
            continue
        fm = _FIELD.match(line)
        if fm and fm.group(1) in MODEL.model_fields:
            out[fm.group(1)] = section
    return out


def _type_name(anno) -> str:
    if get_origin(anno) is list:
        return "list"
    args = [a for a in get_args(anno) if a is not type(None)]
    if args:
        anno = args[0]
    return getattr(anno, "__name__", str(anno))


def _default(field) -> str:
    if field.default_factory is not None:
        return "(dynamic)"
    d = field.default
    if d is None or d is PydanticUndefined:
        return "`(unset)`"
    if d == "":
        return '`""` (empty)'
    return f"`{d}`"


def render() -> str:
    fields = MODEL.model_fields
    sections = _field_sections()
    order, grouped = [], {}
    for name in fields:
        sec = sections.get(name, "General")
        if sec not in grouped:
            grouped[sec] = []
            order.append(sec)
        grouped[sec].append(name)

    out = [f"<!-- {len(fields)} env fields — {_MARKER} -->\n"]
    for sec in order:
        out.append(f"### {sec}\n")
        out.append("| Env var | Default | Type | Purpose |")
        out.append("|---|---|---|---|")
        for name in grouped[sec]:
            field = fields[name]
            env = PREFIX + name.upper()
            typ = _type_name(field.annotation)
            purpose = (field.description or "—").replace("|", "\\|")
            out.append(f"| `{env}` | {_default(field)} | {typ} | {purpose} |")
        out.append("")
    return "\n".join(out)


def main() -> None:
    block = render()
    if "--write" in sys.argv:
        lines = _DOC_PATH.read_text().splitlines(keepends=True)
        cut = next(i for i, l in enumerate(lines) if _MARKER in l)
        _DOC_PATH.write_text("".join(lines[:cut]) + block + "\n")
        print(f"Spliced {block.count('| `')} rows into {_DOC_PATH.relative_to(_ROOT)}")
    else:
        print(block)


if __name__ == "__main__":
    main()
